# ## Log	:	This file is generated by Anlogic Timing Wizard.
# ## File	:	/home/rgwan/anlogic/picorv32_demo/picorv32_demo.sdc
# ## Date	:	09 02 2017

#Created Clock
create_clock -name clk -period 10 [get_ports clk]

